package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"mime/multipart"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/piwi3910/NovaSky/internal/config"
	"github.com/piwi3910/NovaSky/internal/db"
	novaskyRedis "github.com/piwi3910/NovaSky/internal/redis"
)

func main() {
	log.Println("[publisher] Starting...")
	db.Init()
	novaskyRedis.Init()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go func() { c := make(chan os.Signal, 1); signal.Notify(c, syscall.SIGINT, syscall.SIGTERM); <-c; cancel() }()
	novaskyRedis.StartHealthReporter(ctx, "publisher")

	cfg := config.NewManager()
	cfg.Subscribe(ctx)

	ticker := time.NewTicker(5 * time.Minute)
	defer ticker.Stop()

	log.Println("[publisher] Service ready — checking for uploads every 5 minutes")

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			var pubCfg struct {
				Enabled      bool   `json:"enabled"`
				ClientID     string `json:"clientId"`
				ClientSecret string `json:"clientSecret"`
				RefreshToken string `json:"refreshToken"`
				TitleFormat  string `json:"titleFormat"`
				Privacy      string `json:"privacy"`
			}
			cfg.Get("youtube", &pubCfg)

			if !pubCfg.Enabled || pubCfg.RefreshToken == "" {
				continue
			}

			// Check for new timelapses
			tlDir := "/home/piwi/novasky-data/timelapse"
			entries, _ := filepath.Glob(filepath.Join(tlDir, "*.mp4"))
			for _, entry := range entries {
				// Check if already uploaded (marker file)
				marker := entry + ".uploaded"
				if _, err := os.Stat(marker); err == nil {
					continue // already uploaded
				}

				log.Printf("[publisher] Uploading %s to YouTube...", filepath.Base(entry))

				// Get access token from refresh token
				accessToken, err := refreshAccessToken(pubCfg.ClientID, pubCfg.ClientSecret, pubCfg.RefreshToken)
				if err != nil {
					log.Printf("[publisher] Token refresh failed: %v", err)
					continue
				}

				title := time.Now().Format("NovaSky Timelapse 2006-01-02")
				if pubCfg.TitleFormat != "" {
					title = time.Now().Format(pubCfg.TitleFormat)
				}

				privacy := pubCfg.Privacy
				if privacy == "" {
					privacy = "unlisted"
				}

				err = uploadToYouTube(accessToken, entry, title, "Generated by NovaSky", privacy)
				if err != nil {
					log.Printf("[publisher] Upload failed: %v", err)
					continue
				}

				// Mark as uploaded
				os.WriteFile(marker, []byte(time.Now().Format(time.RFC3339)), 0644)
				log.Printf("[publisher] Uploaded: %s", filepath.Base(entry))
			}
		}
	}
}

func refreshAccessToken(clientID, clientSecret, refreshToken string) (string, error) {
	data := fmt.Sprintf("client_id=%s&client_secret=%s&refresh_token=%s&grant_type=refresh_token",
		clientID, clientSecret, refreshToken)

	resp, err := http.Post("https://oauth2.googleapis.com/token", "application/x-www-form-urlencoded",
		bytes.NewBufferString(data))
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	var result struct {
		AccessToken string `json:"access_token"`
		Error       string `json:"error"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	if result.Error != "" {
		return "", fmt.Errorf("oauth error: %s", result.Error)
	}
	return result.AccessToken, nil
}

func uploadToYouTube(accessToken, filePath, title, description, privacy string) error {
	file, err := os.Open(filePath)
	if err != nil {
		return err
	}
	defer file.Close()

	// Create metadata
	metadata, _ := json.Marshal(map[string]any{
		"snippet": map[string]string{
			"title":       title,
			"description": description,
			"categoryId":  "28", // Science & Technology
		},
		"status": map[string]string{
			"privacyStatus": privacy,
		},
	})

	// Multipart upload
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	metaPart, _ := writer.CreatePart(map[string][]string{
		"Content-Type": {"application/json; charset=UTF-8"},
	})
	metaPart.Write(metadata)

	videoPart, _ := writer.CreateFormFile("file", filepath.Base(filePath))
	io.Copy(videoPart, file)
	writer.Close()

	req, _ := http.NewRequest("POST",
		"https://www.googleapis.com/upload/youtube/v3/videos?uploadType=multipart&part=snippet,status",
		body)
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("Content-Type", writer.FormDataContentType())

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("youtube API error %d: %s", resp.StatusCode, string(respBody))
	}
	return nil
}
